<#
.SYNOPSIS
  S23.9 + S23.10 — Ground-truth probe with independent hand-written SQL queries.
  Runs sqlcmd on the remote server against Sepidar01 for 6 core metrics.
  Also runs A/B/C queries for trial_balance to resolve the formula dispute.

.DESCRIPTION
  This script SSHes into the remote server and executes independent,
  hand-written SQL queries via sqlcmd. The queries are NOT generated by
  the engine — they are manually written and documented here.

  Output is saved to scripts/ops/ground-truth-<date>.md

.PARAMETER SshHost
  SSH host (default: 192.168.85.56)

.PARAMETER SshPort
  SSH port (default: 2211)

.PARAMETER SshUser
  SSH user (default: administrator)

.PARAMETER SshPassword
  SSH password

.PARAMETER SqlDatabase
  SQL database name (default: Sepidar01)

.PARAMETER SqlUser
  SQL user (default: damavand)

.PARAMETER SqlPassword
  SQL password (default: damavand)

.PARAMETER FiscalYear
  Persian fiscal year to probe (default: 1402)
#>

param(
  [string]$SshHost = '192.168.85.56',
  [int]$SshPort = 2211,
  [string]$SshUser = 'administrator',
  [string]$SshPassword = 'Hs-co@12321#',
  [string]$HostKey = 'ssh-ed25519 255 SHA256:sEP9p+Bs2vmC7FrAS/CjaodoZVs9LyB2ro4fELRt+iQ',
  [string]$SqlDatabase = 'Sepidar01',
  [string]$SqlUser = 'damavand',
  [string]$SqlPassword = 'damavand',
  [string]$FiscalYear = '1402'
)

$ErrorActionPreference = 'Stop'

# ── Helper: SSH command via plink ─────────────────────────────────────────────
function Invoke-SshCommand {
  param([string]$Command)
  $output = & plink -P $SshPort -ssh -batch -hostkey $HostKey -pw $SshPassword "$SshUser@$SshHost" $Command 2>&1
  return $output
}

function Invoke-RemotePowerShell {
  param([string]$Script)
  $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($Script))
  Invoke-SshCommand "powershell -NoProfile -EncodedCommand $encoded"
}

# ── Helper: Run sqlcmd on remote server ───────────────────────────────────────
function Invoke-SqlcmdRemote {
  param([string]$Sql, [string]$Label)
  Write-Host "  [$Label] executing..." -NoNewline

  # Build a PS1 script that runs Invoke-Sqlcmd on the remote server
  # Avoid nested here-strings — use -EncodedCommand with base64 SQL instead
  $sqlBytes = [Text.Encoding]::Unicode.GetBytes($Sql)
  $sqlB64 = [Convert]::ToBase64String($sqlBytes)

  $remoteScript = "`$ErrorActionPreference = 'Stop';"
  $remoteScript += "`$connStr = 'Server=127.0.0.1,58033;Database=$SqlDatabase;User Id=$SqlUser;Password=$SqlPassword;TrustServerCertificate=True';"
  $remoteScript += "`$sql = [Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('$sqlB64'));"
  $remoteScript += "try { `$result = Invoke-Sqlcmd -ConnectionString `$connStr -Query `$sql -QueryTimeout 120 -ErrorAction Stop;"
  $remoteScript += " if (`$result -and `$result.Column1 -ne `$null) { Write-Output ('RESULT:' + `$result.Column1) }"
  $remoteScript += " else { Write-Output 'RESULT:NULL' } }"
  $remoteScript += " catch { Write-Output ('ERROR:' + `$_.Exception.Message) }"

  $output = Invoke-RemotePowerShell $remoteScript
  $outputStr = ($output | Out-String).Trim()

  if ($outputStr -match '^RESULT:(.+)$') {
    $value = $Matches[1]
    Write-Host " $value" -ForegroundColor Green
    return $value
  } elseif ($outputStr -match '^ERROR:(.+)$') {
    $err = $Matches[1]
    Write-Host " ERROR: $err" -ForegroundColor Red
    return "ERROR: $err"
  } else {
    Write-Host " UNEXPECTED OUTPUT" -ForegroundColor Yellow
    Write-Host "    Raw: $outputStr" -ForegroundColor DarkGray
    return "UNEXPECTED: $outputStr"
  }
}

# ── Independent hand-written SQL queries ──────────────────────────────────────
# These queries are manually written and documented. They are NOT generated
# by the engine. They serve as the first source of truth for ground-truth.

$queries = @(
  @{
    Id    = 'net_sales'
    Label = 'Net Sales (SLS.Invoice)'
    Sql   = "SELECT SUM(NetPriceInBaseCurrency) AS Column1 FROM SLS.Invoice WHERE FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'trial_balance'
    Label = 'Trial Balance — SUM(Debit) with Type NOT IN (3,4)'
    Sql   = "SELECT SUM(vi.Debit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId WHERE v.Type NOT IN (3, 4) AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'account_balance'
    Label = 'Account Balance (Cash 01%) — SUM(Debit-Credit) with Type NOT IN (3,4)'
    Sql   = "SELECT SUM(vi.Debit - vi.Credit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId JOIN ACC.Account a ON vi.AccountSLRef = a.AccountId WHERE v.Type NOT IN (3, 4) AND a.Code LIKE '01%' AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'total_expenses'
    Label = 'Total Expenses — SUM(Debit-Credit) code 61% with Type NOT IN (3,4)'
    Sql   = "SELECT SUM(vi.Debit - vi.Credit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId JOIN ACC.Account a ON vi.AccountSLRef = a.AccountId WHERE v.Type NOT IN (3, 4) AND a.Code LIKE '61%' AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'cash_bank_balance'
    Label = 'Cash + Bank Balance (RPA tables)'
    Sql   = "SELECT (SELECT ISNULL(SUM(Balance), 0) FROM RPA.CashBalance) + (SELECT ISNULL(SUM(Balance), 0) FROM RPA.BankAccountBalance) AS Column1"
  },
  @{
    Id    = 'receivables'
    Label = 'Receivables — SUM(Debit-Credit) accounts 12%/13% with Type NOT IN (3,4)'
    Sql   = "SELECT SUM(vi.Debit - vi.Credit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId JOIN ACC.Account a ON vi.AccountSLRef = a.AccountId WHERE v.Type NOT IN (3, 4) AND (a.Code LIKE '12%' OR a.Code LIKE '13%') AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  }
)

# S23.10 — Trial balance A/B/C queries to resolve the formula dispute
$trialBalanceABC = @(
  @{
    Id    = 'trial_balance_A'
    Label = 'A: SUM(Debit) with v.Type NOT IN (3,4) — excludes closing'
    Sql   = "SELECT SUM(vi.Debit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId WHERE v.Type NOT IN (3, 4) AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'trial_balance_B'
    Label = 'B: SUM(Debit) WITHOUT Type filter — includes closing'
    Sql   = "SELECT SUM(vi.Debit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId WHERE v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'trial_balance_C_debit'
    Label = 'C: SUM(Debit) vs SUM(Credit) with Type NOT IN (3,4) — Debit side'
    Sql   = "SELECT SUM(vi.Debit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId WHERE v.Type NOT IN (3, 4) AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  },
  @{
    Id    = 'trial_balance_C_credit'
    Label = 'C: SUM(Debit) vs SUM(Credit) with Type NOT IN (3,4) — Credit side'
    Sql   = "SELECT SUM(vi.Credit) AS Column1 FROM ACC.VoucherItem vi JOIN ACC.Voucher v ON vi.VoucherRef = v.VoucherId WHERE v.Type NOT IN (3, 4) AND v.FiscalYearRef = (SELECT FiscalYearId FROM FMK.FiscalYear WHERE Title = N'$FiscalYear')"
  }
)

# ── Main ──────────────────────────────────────────────────────────────────────
$dateStr = Get-Date -Format 'yyyy-MM-dd'
$outputFile = "scripts\ops\ground-truth-$dateStr.md"

Write-Host '═══════════════════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host "  GROUND-TRUTH PROBE — S23.9 + S23.10" -ForegroundColor Cyan
Write-Host "  Server: $SshHost`:$SshPort" -ForegroundColor Cyan
Write-Host "  SQL: 127.0.0.1:58033 ($SqlDatabase)" -ForegroundColor Cyan
Write-Host "  Fiscal Year: $FiscalYear" -ForegroundColor Cyan
Write-Host '═══════════════════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host ''

$results = @()

# ── Part 1: 6 core metrics ────────────────────────────────────────────────────
Write-Host '── Part 1: 6 Core Metrics (independent sqlcmd) ──' -ForegroundColor Yellow
foreach ($q in $queries) {
  $value = Invoke-SqlcmdRemote -Sql $q.Sql -Label $q.Label
  $results += [PSCustomObject]@{
    Id    = $q.Id
    Label = $q.Label
    Value = $value
    Sql   = $q.Sql
  }
}

# ── Part 2: Trial balance A/B/C (S23.10) ──────────────────────────────────────
Write-Host ''
Write-Host '── Part 2: Trial Balance A/B/C (S23.10 — formula dispute) ──' -ForegroundColor Yellow
$abcResults = @()
foreach ($q in $trialBalanceABC) {
  $value = Invoke-SqlcmdRemote -Sql $q.Sql -Label $q.Label
  $abcResults += [PSCustomObject]@{
    Id    = $q.Id
    Label = $q.Label
    Value = $value
    Sql   = $q.Sql
  }
}

# ── Generate markdown report ──────────────────────────────────────────────────
Write-Host ''
Write-Host '── Generating report ──' -ForegroundColor Yellow

$md = @()
$md += "# Ground-Truth Probe — $dateStr"
$md += ""
$md += "## S23.9 — 6 Core Metrics (independent sqlcmd)"
$md += ""
$md += "| Metric | Label | Value |"
$md += "|--------|-------|-------|"
foreach ($r in $results) {
  $md += "| $($r.Id) | $($r.Label) | $($r.Value) |"
}
$md += ""

$md += "### SQL Queries (hand-written, independent of engine)"
$md += ""
foreach ($r in $results) {
  $md += "#### $($r.Id)"
  $md += "```sql"
  $md += $r.Sql
  $md += "```"
  $md += ""
}

$md += "## S23.10 — Trial Balance A/B/C (formula dispute resolution)"
$md += ""
$md += "| Query | Label | Value |"
$md += "|-------|-------|-------|"
foreach ($r in $abcResults) {
  $md += "| $($r.Id) | $($r.Label) | $($r.Value) |"
}
$md += ""

$md += "### Analysis"
$md += ""
$md += "- **A** (Type NOT IN 3,4): SUM(Debit) excluding closing entries"
$md += "- **B** (no Type filter): SUM(Debit) including closing entries"
$md += "- **C_debit** vs **C_credit**: If Debit ≈ Credit with Type NOT IN (3,4), then A is the correct trial balance formula"
$md += ""
$md += "### Conclusion"
$md += ""
$md += "_(To be filled after reviewing results above)_"
$md += ""

$md | Set-Content -Path $outputFile -Encoding UTF8

Write-Host "  Report saved to: $outputFile" -ForegroundColor Green
Write-Host ''
Write-Host '═══════════════════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host '  DONE — Review the report and fill in the conclusion.' -ForegroundColor Cyan
Write-Host '═══════════════════════════════════════════════════════════' -ForegroundColor Cyan
