import assert from 'node:assert/strict'
import { test } from 'node:test'

import { AgentOrchestrator } from '../../src/main/services/agentOrchestrator'
import { DEFAULT_SETTINGS } from '../../src/main/types'

/**
 * Test helper to mock executeReadOnlySql and record query strings.
 * This allows us to verify the exact SQL generated by deterministic paths
 * without requiring a real database connection.
 */
class SqlQueryRecorder {
  private queries: string[] = []

  record(query: string): void {
    this.queries.push(query)
  }

  getQueries(): string[] {
    return this.queries
  }

  getLastQuery(): string | undefined {
    return this.queries[this.queries.length - 1]
  }

  clear(): void {
    this.queries = []
  }
}

function createMockAgentOrchestrator(recorder: SqlQueryRecorder): AgentOrchestrator {
  const settings = structuredClone(DEFAULT_SETTINGS)
  settings.sql.database = 'Sepidar01'
  settings.sql.server = '127.0.0.1'
  settings.sql.port = 58033
  settings.sql.user = 'damavand'
  settings.sql.password = 'test'

  const orchestrator = new AgentOrchestrator({
    geminiClient: {
      chat: async () => ({
        text: '',
        raw: {},
        toolCalls: []
      })
    },
    getSettings: () => settings,
    executeReadOnlySql: async (query: string) => {
      recorder.record(query)
      return []
    },
    executeMetadataSql: async () => [],
    auditLog: {
      write: async () => undefined
    }
  })

  return orchestrator
}

test('U0.3: get_trial_balance should use [schema].[table] quoting, not [schema.table]', async () => {
  const recorder = new SqlQueryRecorder()
  const orchestrator = createMockAgentOrchestrator(recorder)

  const settings = orchestrator['getSettings']()
  const conversationMemory = {
    conversationId: 'test',
    notes: [],
    facts: {
      companyNames: [],
      fiscalYears: [],
      branchNames: [],
      dateRange: null,
      confirmedMappings: {}
    },
    lastUserPrompt: 'تراز آزمایشی سال ۱۴۰۲',
    lastAssistantOutcome: null,
    lastToolTrace: [],
    touchedAt: Date.now()
  }
  await orchestrator['tryResolveDeterministicFinancialTool'](
    'get_trial_balance',
    settings,
    conversationMemory,
    new AbortController().signal
  )

  const query = recorder.getLastQuery()
  assert.ok(query, 'A SQL query should have been generated')

  // The query should use [ACC].[VoucherItem] and [ACC].[Voucher], NOT [ACC.VoucherItem] or [ACC.Voucher]
  assert.ok(
    query!.includes('[ACC].[VoucherItem]'),
    `Query should contain [ACC].[VoucherItem] but got: ${query}`
  )
  assert.ok(
    query!.includes('[ACC].[Voucher]'),
    `Query should contain [ACC].[Voucher] but got: ${query}`
  )
  assert.ok(
    !query!.includes('[ACC.VoucherItem]'),
    `Query should NOT contain [ACC.VoucherItem] but got: ${query}`
  )
  assert.ok(
    !query!.includes('[ACC.Voucher]'),
    `Query should NOT contain [ACC.Voucher] but got: ${query}`
  )
})

test('U0.4: get_account_balance should use [schema].[table] quoting', async () => {
  const recorder = new SqlQueryRecorder()
  const orchestrator = createMockAgentOrchestrator(recorder)

  const settings = orchestrator['getSettings']()
  const conversationMemory = {
    conversationId: 'test',
    notes: [],
    facts: {
      companyNames: [],
      fiscalYears: [],
      branchNames: [],
      dateRange: null,
      confirmedMappings: {}
    },
    lastUserPrompt: 'مانده بدهکار حساب بانک',
    lastAssistantOutcome: null,
    lastToolTrace: [],
    touchedAt: Date.now()
  }
  await orchestrator['tryResolveDeterministicFinancialTool'](
    'get_account_balance',
    settings,
    conversationMemory,
    new AbortController().signal
  )

  const query = recorder.getLastQuery()
  assert.ok(query, 'A SQL query should have been generated')

  assert.ok(
    query!.includes('[ACC].[VoucherItem]'),
    `Query should contain [ACC].[VoucherItem] but got: ${query}`
  )
  assert.ok(
    query!.includes('[ACC].[Voucher]'),
    `Query should contain [ACC].[Voucher] but got: ${query}`
  )
  assert.ok(
    !query!.includes('[ACC.VoucherItem]'),
    `Query should NOT contain [ACC.VoucherItem] but got: ${query}`
  )
})

test('U0.4: get_cash_bank_balance should use [schema].[table] quoting', async () => {
  const recorder = new SqlQueryRecorder()
  const orchestrator = createMockAgentOrchestrator(recorder)

  const settings = orchestrator['getSettings']()
  const conversationMemory = {
    conversationId: 'test',
    notes: [],
    facts: {
      companyNames: [],
      fiscalYears: [],
      branchNames: [],
      dateRange: null,
      confirmedMappings: {}
    },
    lastUserPrompt: 'مانده نقد و بانک',
    lastAssistantOutcome: null,
    lastToolTrace: [],
    touchedAt: Date.now()
  }
  await orchestrator['tryResolveDeterministicFinancialTool'](
    'get_cash_bank_balance',
    settings,
    conversationMemory,
    new AbortController().signal
  )

  const queries = recorder.getQueries()
  assert.ok(queries.length > 0, 'SQL queries should have been generated')

  // Check that all queries use proper [schema].[table] quoting
  for (const query of queries) {
    assert.ok(
      !query.includes('[RPA.CashBalance]'),
      `Query should NOT contain [RPA.CashBalance] but got: ${query}`
    )
    assert.ok(
      !query.includes('[RPA.BankAccountBalance]'),
      `Query should NOT contain [RPA.BankAccountBalance] but got: ${query}`
    )
  }

  // At least one query should use proper quoting
  const hasProperQuoting = queries.some(
    (q) => q.includes('[RPA].[CashBalance]') || q.includes('[RPA].[BankAccountBalance]')
  )
  assert.ok(hasProperQuoting, `At least one query should use [RPA].[CashBalance] or [RPA].[BankAccountBalance]`)
})

test('U2.3: get_account_balance with fiscal year filters by year', async () => {
  const recorder = new SqlQueryRecorder()
  const orchestrator = createMockAgentOrchestrator(recorder)

  const settings = orchestrator['getSettings']()
  const conversationMemory = {
    conversationId: 'test',
    notes: [],
    facts: {
      companyNames: [],
      fiscalYears: [],
      branchNames: [],
      dateRange: null,
      confirmedMappings: {}
    },
    lastUserPrompt: 'مانده بدهکار حساب سال ۱۴۰۲',
    lastAssistantOutcome: null,
    lastToolTrace: [],
    touchedAt: Date.now()
  }
  await orchestrator['tryResolveDeterministicFinancialTool'](
    'get_account_balance',
    settings,
    conversationMemory,
    new AbortController().signal,
    undefined,
    'مانده بدهکار حساب سال ۱۴۰۲'
  )

  const query = recorder.getLastQuery()
  assert.ok(query, 'A SQL query should have been generated')

  assert.ok(
    query!.includes("fy.Title = N'1402'"),
    `Query should contain fiscal year filter fy.Title = N'1402' but got: ${query}`
  )
  assert.ok(
    query!.includes('[ACC].[VoucherItem]'),
    `Query should contain [ACC].[VoucherItem] but got: ${query}`
  )
  assert.ok(
    query!.includes('[FMK].[FiscalYear]'),
    `Query should contain [FMK].[FiscalYear] but got: ${query}`
  )
})

test('U2.4: get_account_balance with account name and fiscal year filters by both', async () => {
  const recorder = new SqlQueryRecorder()
  const orchestrator = createMockAgentOrchestrator(recorder)

  const settings = orchestrator['getSettings']()
  const conversationMemory = {
    conversationId: 'test',
    notes: [],
    facts: {
      companyNames: [],
      fiscalYears: [],
      branchNames: [],
      dateRange: null,
      confirmedMappings: {}
    },
    lastUserPrompt: 'مانده بدهکار حساب بانک سال ۱۴۰۳',
    lastAssistantOutcome: null,
    lastToolTrace: [],
    touchedAt: Date.now()
  }
  await orchestrator['tryResolveDeterministicFinancialTool'](
    'get_account_balance',
    settings,
    conversationMemory,
    new AbortController().signal,
    undefined,
    'مانده بدهکار حساب بانک سال ۱۴۰۳'
  )

  const query = recorder.getLastQuery()
  assert.ok(query, 'A SQL query should have been generated')

  assert.ok(
    query!.includes("fy.Title = N'1403'"),
    `Query should contain fiscal year filter fy.Title = N'1403' but got: ${query}`
  )
  assert.ok(
    query!.includes("a.Title LIKE N'%بانک%'"),
    `Query should contain account name filter a.Title LIKE N'%بانک%' but got: ${query}`
  )
  assert.ok(
    query!.includes('[ACC].[Account]'),
    `Query should contain [ACC].[Account] when filtering by account name but got: ${query}`
  )
})

test('U4.4: isSalesGrowthPercentPrompt triggers for comparative multi-period without %', async () => {
  const recorder = new SqlQueryRecorder()
  const orchestrator = createMockAgentOrchestrator(recorder)

  // Test that comparative multi-period prompts (e.g., "فروش 1403 در مقابل 1402")
  // trigger the sales growth percentage path even without explicit '%' keyword
  const prompt1 = 'فروش 1403 در مقابل 1402'
  const prompt2 = 'مقایسه فروش سال 1402 و 1403'
  const prompt3 = 'فروش 1403 نسبت به 1402'

  assert.ok(
    orchestrator['isSalesGrowthPercentPrompt'](prompt1),
    `Prompt "${prompt1}" should trigger sales growth percentage path`
  )
  assert.ok(
    orchestrator['isSalesGrowthPercentPrompt'](prompt2),
    `Prompt "${prompt2}" should trigger sales growth percentage path`
  )
  assert.ok(
    orchestrator['isSalesGrowthPercentPrompt'](prompt3),
    `Prompt "${prompt3}" should trigger sales growth percentage path`
  )
})
